export { default as Navbar } from '../../cw2/Components/Navbar/Navbar'
export { default as Hero } from '../../cw2/Components/Hero/Hero'
export { default as Info } from '../../cw2/Components/Info/Info'
export { default as Footer } from '../../cw2/Components/Footer/Footer'
export { default as SignUp } from '../../cw2/Components/Login&Register/SignUp'
